version: "3.8"

networks:
 poc:

volumes:
  postgres_data:
      driver: local

services:
  kong:
    container_name: kong-dbless
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - poc
    depends_on:
      - keycloak
    environment:
      - KONG_DATABASE=off
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_PLUGINS=bundled,jwt-keycloak
      - KONG_DECLARATIVE_CONFIG=/usr/local/etc/kong/kong.yml
    ports:
      - "8001:8001"
      - "8444:8444"
      - "80:8000"
      - "443:8443"
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - poc      
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      container_name: keycloak
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        PROXY_ADDRESS_FORWARDING: true
        KC_HOSTNAME: localhost
        KC_HOSTNAME_PATH: auth
        KC_HOSTNAME_ADMIN: localhost
        KC_HOSTNAME_PORT: 443
      ports:
        - 8080:8080
      depends_on:
        - postgres
      networks:
        - poc
